<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Discount.Application\Discount.Application.csproj" />
      <ProjectReference Include="..\Discount.Infrastructure\Discount.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- gRPC proto reference -->
        <Protobuf Include="..\Application\Protos\discount.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
        <!-- Reference Application layer -->
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
